language: java
jdk:
  - openjdk6
  - openjdk7
before_install:
  - sudo pip install nose
  - sudo pip install -e git+https://github.com/pdef/pdef.git@1.2#egg=pdef-compiler==1.2
install:
  - sh -c 'cd generator && sudo python setup.py install'
script:
  - sh -c 'cd generator && nosetests'
  - mvn test

