language: java
jdk:
  - openjdk6
  - openjdk7
before_install:
  - sudo pip install nose
install:
  - sh -c 'cd generator && sudo python setup.py install'
script:
  - sh -c 'cd generator && nosetests'
  - mvn test

