language: java
jdk:
  - openjdk6
before_install:
  - sh -c 'cd generator && sudo python setup.py install && cd ../'
  - sudo pip install nose
script:
  - nosetests generator
  - sh -c 'cd java && mvn test && cd ../'
